#!/usr/bin/env zsh

heading "Customizing the Dock..."

# ✅ Remove all dock items
dockutil --remove all --no-restart

# ✅ Add links to desktop and Box
dockutil --add "/" --view grid --display folder --no-restart
dockutil --add "$HOME/Desktop" --view grid --display folder --no-restart

# ✅ Add back apps in the order we care about
dockutil --add /System/Applications/System\ Settings.app --no-restart
dockutil --add /Application/Google\ Chrome.app/ --no-restart
dockutil --add /System/Applications/Messages.app --no-restart
