#!/usr/bin/env zsh

heading "Installing Homebrew..."

# ✅ Install Homebrew
yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# ✅ Add Homebrew to Path
echo >>"${HOME}/.zprofile"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>"${HOME}/.zprofile"
eval "$(/opt/homebrew/bin/brew shellenv)"

# ✅ Update Homebrew
brew update
brew upgrade
