#!/usr/bin/env zsh

# ✅ Install a few of my favorite local LLMs
download_jan_model "unsloth" "Qwen3-4B-Thinking-2507-GGUF" "Qwen3-4B-Thinking-2507-Q4_K_M.gguf"
download_jan_model "prithivMLmods" "Bootes-Qwen3_Coder-Reasoning-Q4_K_M-GGUF" "Bootes-Qwen3_Coder-Reasoning-Q4_K_M.gguf"
download_jan_model "bartowski" "Qwen_Qwen3-VL-4B-Thinking-GGUF" "Qwen_Qwen3-VL-4B-Thinking-Q4_K_M.gguf"
